version: '2'
services:
  db:
     image: mysql:5.7
     volumes:
       - mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root_wpress_247x
       MYSQL_DATABASE: rds_mysql  
       MYSQL_USER: wpress 
       MYSQL_PASSWORD: wpress_247x 
     container_name: wp_mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress:/var/www/html/
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpress
      WORDPRESS_DB_PASSWORD: wpress_247x
      WORDPRESS_DB_NAME: rds_mysql
    container_name: wp_site

  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/ssl/my_wpress_site.cert:/etc/nginx/my_wpress_site.cert"
      - "./nginx/ssl/my_wpress_site.key:/etc/nginx/my_wpress_site.key"
      - "/var/log/nginx:/var/log/nginx"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    links:
      - wordpress
    restart: unless-stopped
    container_name: wp_nginx

volumes:
  mysql:
  wordpress:
